### ISSUE TITLE
What is the actual size in user download?

### ISSUE THREAD

**Issue by top2tech** [twilio/video-quickstart-swift#124]
I archived video-quickstart-swift, the file size if 277MB. I know it's bitcode, so the actual size in user download will be smaller, but how much it will be roughly? 

This is important so we don't have too big file to discourage users from downloading.

The installed size on my iPhone 7 plus of video-quickstart-swift is around 150MB.
Before the bitcode version of twilio video, the installed size is around 50MB.

As a comparison, on the same iPhone, Periscope app (live video broadcast) installed size is 62MB, and House Party app (p2p video chat) is 38MB.

If bitcode brings 3X size, and 100MB additional download size. Looks like the benefit of bitcode is not worthwhile, at least before Apple change bitcode from recommended to mandatory.

So, at least, is it possible to provide a twilio video framework version without bitcode?

**Comment by ceaglest** [comment]
Hi @top2tech,

This is a very good question, and something that we should include in our documentation. I've asked one of our team members to submit an app containing the Twilio Video SDK to the app store (including Bitcode) so that we can see the final size. I will update this ticket, and our docs once we have this info. In general, Bitcode should not increase the size of the downloadable App and these extra sections are provided so that Apple can re-compile your app dynamically after you submit it.

> So, at least, is it possible to provide a twilio video framework version without bitcode?

If you don't want to use Bitcode, please see the sample Podfile I provided in https://github.com/twilio/video-quickstart-swift/issues/110. It's possible to strip the Bitcode sections, at least until Apple makes Bitcode a hard requirement.

Best,
Chris Eagleston

**Comment by ceaglest** [comment]
Hi @top2tech,

We haven't done an app store submission yet, but I did follow the instructions from Apple on [generating an app sizing report](https://developer.apple.com/library/content/qa/qa1795/_index.html). To get a baseline for comparison I used our Objective-C QuickStart app, which doesn't require including the Swift 3 runtime. CocoaPods was used to install TwilioVideo, which automatically strips the simulator architectures.

#### Size Estimate

Twilio Video 1.0.0

armv7: 4.4 MB compressed, 8.5 MB uncompressed
arm64: 4.2 MB compressed, 10.1 MB uncompressed
universal: 8.5 MB compressed, 18.6 MB uncompressed

The final download size that your users will see depends on what Device and OS combination they use, as app thinning is only supported on iOS 9.0 and above. Also, the estimate doesn't include any size increase from encryption added once your app is approved for sale.

[App Thinning Size Report.txt](https://github.com/twilio/video-quickstart-swift/files/998435/App.Thinning.Size.Report.txt)

Best,
Chris Eagleston

**Comment by ceaglest** [comment]
Hi @top2tech,

This is an old issue, but I'm happy to report that, starting with [2.5.4](https://github.com/twilio/twilio-video-ios/releases/tag/2.5.4) we are now publishing size estimates with each release of the Video SDK. You will also find that the framework artifact includes a size impact report generated with xcodebuild.

Now that this is part of our CI / CD process you can expect that future releases will also contain these reports.

Regards,
Chris

Regards,
Chris
