### ISSUE TITLE
Twilio video quality adjustable or not?

### ISSUE THREAD

**Issue by weyi-rzl** [twilio/video-quickstart-swift#137]
After integrating Twilio Video sdk with my app, I found once the network turns slower(or WIFI to 4G handoff), the stream becomes really low-quality, however the process is not reversible when the Internet speeds up. In this case, is there anyway to make the stream quality adjustable according to the network speed?

**Comment by ceaglest** [comment]
Hi @weyi-rzl,

The answer is yes, the quality of video you send and receive varies depending on your network conditions. The media engine may choose to downscale temporally or spatially if it determines that there is not enough bandwidth available. Even if no downscaling is needed the number of bits that the encoder is allocated are determined dynamically using bandwidth estimation. If network conditions improve, the downscaling should be removed and more bits allocated resulting in higher quality.

**Split Media & Signaling**

However, we are currently tracking a bug where the signaling and media connections can be split across different network interfaces after a handoff occurs. For example, imagine three networks.

Wifi A
Cell B
Wifi C

Your device starts with a connection to Wifi A, and Cell B. The device connects to a Room and media and signaling use Wifi A. Then the device loses connection to Wifi A, causing media to transition to Cell B. Next, the device joins Wifi C. At this point signaling is re-established on Wifi C but since the candidates gathered on the cellular interface are still valid it never gathers candidates on Wifi C. Instead of using Wifi C for media, Cell B is used.

A few questions:

1. What version of Twilio Video are you using?
2. What device(s) are being used?
3. Can you provide logs of the SDK and WebRTC module when you experience the problem?

```
TwilioVideo.setLogLevel(TVILogLevel.info)
TwilioVideo.setLogLevel(TVILogLevel.info, module: TVILogModule.webRTC)
```

>  I found once the network turns slower(or WIFI to 4G handoff), the stream becomes really low-quality, however the process is not reversible when the Internet speeds up.

If the slowdown / congestion is on the original network and no handoff has occurred then the problem should resolve itself once the congestion clears up. If handoff like I described above has occurred it could be an issue with split media / signaling and using the cellular connection when a new wifi network should be preferred.

I'm happy to take a look if you can provide the info I requested. As for the split media / signaling we are actively investigating this issue.

Best,
Chris Eagleston

**Comment by weyi-rzl** [comment]
Hi, @ceaglest ,
Thank you for the reply, that really explains things to me. Currently, I'm using version 1.0.0, and mostly I'm using iPhone 6s running  iOS 10.2, and the log is not available at this moment, my apology.
For next step,I'll update the Twilio Video SDK and give it more try on scenarios with no handoff occurring.
Thank you again for the explanation.

**Comment by weyi-rzl** [comment]
Hi, @ceaglest,
Here is another interesting issue I found during the test, the quality of local video (captured from the phone camera) can be adjustable according to the network, let's say, once the network speed drops, the local video quality could become really bad, the picture is pixelated. It seems like stream transferring from A to B is of the similar quality when showing on both ends.
Just so you know, I'm using TVILocalVideoTrack and TVICameraCapturer to do the local video capturing work (referred to the Twilio VIdeo quickstart project). Is there any better way other than using iOS framework to catch the local image? I want to make the local stream be not interfered by the network condition changes.
Thank you.

**Comment by ceaglest** [comment]
Hi @weyi-rzl,

Yes, this is expected at least when using the Metal TVIVideoView implementation. When spatial downscaling is requested it is performed at the front end of the capture pipeline. In the case of the Metal implementation it doesn't yet support zero copy so it gets the downscaled, and format converted frames to render. Once we support zero copy in Metal you won't see the local video being downscaled. If you don't want this today you could try using `TVICameraPreviewView` instead of `TVIVideoView` to render local video. In order to enable camera preview you need to use the `initWithSource:delegate:enablePreview` initializer for `TVICameraCapturer` and then add the `previewView` to your view hierarchy in place of `TVIVideoView`.

Best,
Chris

**Comment by ptankTwilio** [comment]
@weyi-rzl We have fixed issue of split media (i.e. after handover from cellular data to wifi, media still uses the cellular data) in version 1.1.0 ([changelogs](https://www.twilio.com/docs/api/video/changelogs/ios#110-june-27-2017)). I would encourage you to try our latest SDK. I am closing the ticket but feel free to reopen it if you observe the problem again. 

Thanks,
Piyush
