### ISSUE TITLE
Twilio logs error: Failed to get a drawable!

### ISSUE THREAD

**Issue by alexiss03** [twilio/video-quickstart-swift#140]
Hi!

When trying to connect to a room, I am intermittently receiving repeating logs "Failed to get a drawable!", then the touches are not recognized. However, some attempts to connect were successful. I am running my app on an iPad mini running on iOS 8.2. The same source code works on iOS 9, and iOS 10. Upon researching, this kind of error is related with Apple's Metal. I hope you can help me in finding the root cause of this error.

Thanks,
Lexi

**Comment by ptankTwilio** [comment]
@alexiss03 I am assuming you are using 64-bit (iPad mini 2 or greater) iPad mini, please confirm this. In SDK, Metal video renderer throws the error "Failed to get a drawable!" when the render pass descriptor can not find a drawable from metal layer. 

In order to debug this problem further, can you provide following - 

1. Are you able to reproduce the problem on QuickStart?
2. You said the problem is not reproducible on iOS 9 and 10. Did you try on the same type of device -  iPad mini with iOS 9 and 10 ?
3. Is it possible for you to share shot and screen stack on Xcode debugger when problem reproduces?

Regards,
- Piyush

**Comment by alexiss03** [comment]
Hi Piyush!

Yes, I am using a 64-bit iPad mini for debugging. I was not able to replicate the same error in the QuickStart project. Upon further investigation, this error only occurs when the device is connected to Xcode's debugger, everything works fine when disconnected. I am closing this issue because this is more related to the debugger's performance on iOS 8. 

Thanks.
Lexi
