### ISSUE TITLE
Access Token from Twilio API from iOS Side

### ISSUE THREAD

**Issue by Nik20112** [twilio/video-quickstart-swift#144]
Hi,
I want to know that is there any way I can generate the Access Token from Twilio API from iOS Side not Server Side then I can use this access token in my video call application. Please give me asap.

Thanks
Nikunj

**Comment by ceaglest** [comment]
Hi @Nik20112,

While it is certainly possible to generate a JWT access token on an iOS Client we do not recommend this practice. In order to sign a token you would need to include several pieces of sensitive information in your iOS application, namely:

AccountSid
AccountSecret
ApiKey

Once you've distributed your software to the App Store, TestFlight, HockeyApp, or others than its entirely possible for a malicious party to gain access to this information. For further reading check out our [User Identity & Access Tokens guide](https://www.twilio.com/docs/api/video/user-identity-access-tokens).

If issuing tokens on device is something you want to do for internal testing purposes, there are several JWT generation libraries available such as:

https://github.com/yourkarma/JWT
https://github.com/kylef/JSONWebToken.swift

Regards,
Chris Eagleston

**Comment by ceaglest** [comment]
Hi @Nik20112,

I hope my response was helpful. Please let me know if there is anything else you need.

Best,
Chris Eagleston
