### ISSUE TITLE
Send second source of audio to remote participant

### ISSUE THREAD

**Issue by kcedric** [twilio/video-quickstart-swift#182]
Hi,

I'm trying to send a second source of audio (streamed from a bluetooth connected device as Int16 data flow) to a room using twilio-video on iOS.

I already looked at TVIAudioController but found nothing about audioInput.
Checked-out also TVIAudioSink but I don't know if it can do the job. 

Anyone can help ?

**Comment by ptankTwilio** [comment]
@kcedric Video SDK uses the default device given by iOS when an external audio source is attached. Can you provide more details about your used case?  Please note that video SDK supports Bluetooth audio device however audio from two audio sources at the same time is not supported by the SDK.

**Comment by kcedric** [comment]
@ptankTwilio Actually I have a twilio-video streaming from iOS device using camera and default local audio track

Then, I connect a bluetooth medical device which is a stetoscope and it sends audio data as an array of Int16.

I need then to "give" this audio data to twilio video in order to send it the remote participant.
Is this possible ?

**Comment by ptankTwilio** [comment]
@kcedric At present, our Video SDK does not support the feature where you can "give" audio data to the SDK. We are planning to add this feature as we have received requests from few other customers as well. I will post the updates about this feature on this ticket. Thank you.

**Comment by kcedric** [comment]
thanks for the infos, the feature would be very much appreciated !

**Comment by ptankTwilio** [comment]
We have just released 2.0.0-preview8 with new Audio APIs. The 2.0.0-preview8 provides a block property in TVIDefaultAudioSession class. You can configure AVAudioSession with the configuration your choice inside the block.

2.0.0-preview8 Changelogs - https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-2x#200-preview8-january-9-2018

Few example usages:
https://github.com/twilio/video-quickstart-objc/tree/2.0.0-preview/AVPlayerExample
https://github.com/twilio/video-quickstart-swift/tree/master/VideoCallKitQuickStart

Please note that the 2.0.0-preview8 does not solve your used case, however, 2.0.0-preview8 is the first release of our new Audio APIs. We will release more features in future releases where you can provide audio samples to the SDK.

I would recommend using 2.0.0-preview8. Let me know if you have any questions.

**Comment by ceaglest** [comment]
Hey @kcedric,

I know it's been a while since you requested this, but if you're still interested in streaming from a bluetooth medical device that doesn't implement one of the standard audio protocols (HFP etc.) you could try our new AudioDevice APIs.

We've just released [2.0.0-beta1](https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-2x#200-beta1-february-7-2018) and an [example](https://github.com/twilio/video-quickstart-swift/tree/master/AudioDeviceExample) of a custom device. You could probably accomplish what you need by implementing `TVIAudioDeviceCapturer` and feeding in the `Int16` data that you receive over bluetooth as 16-bit signed LPCM audio.

Regards,
Chris Eagleston

**Comment by ceaglest** [comment]
Since this issue is pretty old I'm going to close it out. If you have any more questions in this area feel free to re-open the issue.

Thanks,
Chris
