### ISSUE TITLE
How to avoid black bars in TVIVideoView ?

### ISSUE THREAD

**Issue by pravishanth** [twilio/video-quickstart-swift#186]
Getting black bars (on top and bottom of the video) when rendering videoTrack in videoView (TVIVideoView), I ensured that videoView dimensions are set to screen dimensions (see `function configureVideoView()`).  
I believe the issue is with the way videoTrack is rendered ? (See below `participant addedVideoTrack` function) 

```
let mainScreenSize  : CGRect = UIScreen.main.bounds
let mainScreenWidth  : CGRect = mainScreenSize.width
let mainScreenWidth  : CGRect = mainScreenSize.height

var videoView       : TVIVideoView! // To show remote user video

func configureVideoView(){
        videoView = TVIVideoView.init(frame: CGRect.zero, delegate: self)
        videoView.frame.width =  mainScreenWidth
        videoView.frame.height =  mainScreenHeight
}

func participant(_ participant: TVIParticipant, addedVideoTrack videoTrack: TVIVideoTrack) {
        if (self.participant == participant) {
            videoTrack.addRenderer(videoView) // The video track will be added to the videoView i.e self
        }
    }
```

**Comment by paynerc** [comment]
Good morning!

The issue is that the dimensions of the video that you are attempting to display does not match the dimensions of the view in which you wish to display it in. You can use different `contentMode` settings on the `TVIVideoView` to configure how the video is displayed. `TVIVideoView` supports [`UIViewContentModeScaleToFill`](https://developer.apple.com/documentation/uikit/uiviewcontentmode/uiviewcontentmodescaletofill), [`UIViewContentModeScaleAspectFill`](https://developer.apple.com/documentation/uikit/uiviewcontentmode/uiviewcontentmodescaleaspectfill) and [`UIViewContentModeScaleAspectFit`](https://developer.apple.com/documentation/uikit/uiviewcontentmode/uiviewcontentmodescaleaspectfit) content modes.

Let me know if you have any further questions.

Ryan

**Comment by pravishanth** [comment]
@paynerc  Thanks.. it works!!
