### ISSUE TITLE
Why does 'timedOutPerformingAction' get called ?

### ISSUE THREAD

**Issue by pravishanth** [twilio/video-quickstart-swift#196]
Scenario: "Alice calls Bob, Alice and Bob are connected to the room and can see each others video".

Issue: Cannot hear each others Audio and `timedOutPerformingAction` delegate method gets called and call ends.

For Info:
a. Local audio track is created for Bob and Alice.   
b.`TVIParticipant addedAudioTrack` delegate method gets called for Bob and Alice.

Looked up apple docs on CallKit for [timedOutPerformingAction](https://developer.apple.com/documentation/callkit/cxproviderdelegate/1771738-provider?language=objc) which says: 
> Called when the provider performs the specified action times out.

Not sure what to make of it.

**Comment by pravishanth** [comment]
@ptankTwilio, I would really appreciate if you can advice on this issue which completely blocks us from using Twilio video call service.

look forward to hear from you.

**Comment by ptankTwilio** [comment]
@pravishanth Can you provide more details which action is getting timed out by inspecting the `CXAction` returned in `timedOutPerformaingAction`? 

Regarding the no audio: since CallKit activates the AVAudioSession, it's important to use `TVIAudioController`'s  CallKit APIs appropriately in the app. I would recommend comparing your application code with the [VideoCallKitQuickStart](https://github.com/twilio/video-quickstart-swift/tree/master/VideoCallKitQuickStart) example to debug the issue in your application.

**Comment by pravishanth** [comment]
@ptankTwilio, 
Apologies for the delay in reporting back,
 
I tried to print the CXAction returned in 
` func provider(_ provider: CXProvider, timedOutPerforming action: CXAction) {
logMessage("Action in timedOutPerformingAction: \(action)")
}`

This is what I get, could not understand what `failureReason=2` means,
`<CXAnswerCallAction 0x14f3a730 UUID=DA5B2D26-CEDD-49A6-A2D3-7E29953659AF state=2 commitDate=2017-11-13 05:45:25 +0000 failureReason=2 callUUID=7DC79500-A97E-47B8-BE5B-1C98403FACA9 localLandscapeAspectRatio={0, 0} localPortraitAspectRatio={0, 0} dateConnected=(null)>`

I also compared my code against  [VideoCallKitQuickStart](https://github.com/twilio/video-quickstart-swift/tree/master/VideoCallKitQuickStart), and I can confirm that there are no changes in the way `TVIAudioController` is configured.

**Comment by ptankTwilio** [comment]
@pravishanth I am suspecting the AnswerCallAction is not being fulfilled in your app and that's why it is timing out. So, can you make sure your app is calling `fulfill` on CXAnswerCallAction? Our quickstart example executes the `[CXAnswerCallAction fullfill]` upon receiving the `TVIRoomDelegate `'s `didConnectToRoom` callback.

see following for reference :

https://github.com/twilio/video-quickstart-swift/blob/master/VideoCallKitQuickStart/ViewController%2BCallKit.swift#L73

https://github.com/twilio/video-quickstart-swift/blob/master/VideoCallKitQuickStart/ViewController.swift#L285

**Comment by pravishanth** [comment]
@ptankTwilio,

You were bang on, thanks so much for the advice.
The AnswerCallAction wasn't being fulfilled, since my `performRoomConnect function` wasn't passing a value to the callback.

**Comment by fukemy** [comment]
thanks, i know problem, i must call reportOutgoingCallWithUUID
