### ISSUE TITLE
TVIAudioSink.renderSample not beeing called after reconnect

### ISSUE THREAD

**Issue by artemtarassov** [twilio/video-quickstart-swift#215]
Hi,

i work with TwilioVideo (1.3.8) on an iPhone 7 iOS 11.2 (UserA) and IPhone 6 iOS 11.2 (UserB).
UserA and UserB join the same Room. Here is what happens on UserB device:

I'm using TVIAudioSink->renderSample to get the audio data and TVIVideoRenderer->renderFrame to get the frames from the local tracks. Everything works fine so far.
When i call room.disconnect() and remove all the views, i can log that in my class that is implementing TVIVideoRenderer the renderFrame method is always beeng called - no matter if i'm connected or disconnected.
I'm not sure if this is normal, so what i do now is calling removeSink and removeRenderer before the disconnect.

It seemed that the problem was solved. But now, when i reconnect to the same room i was in before, the TVIVideoRenderer does not get any renderSample calls. I see that the TVIVideoRenderer receives his renderFrame calls, but the TVIAudioSink remains silent.

If i restart the app and then connect to the same room again, the TVIAudioSink works as intended.
My guess is that there is something wrong with the disconnect, so a new connection after the disconnect might cause some issues.

Can you help me with this?
- is it normal that renderFrame is beeing called after disconnect?
- Why is TVIAudioSink->renderSample not beeing called the second time i connect?

Thanks!

**Comment by ceaglest** [comment]
Hi @artemtarassov,

> When i call room.disconnect() and remove all the views, i can log that in my class that is implementing TVIVideoRenderer the renderFrame method is always beeng called - no matter if i'm connected or disconnected.

Yes, this is expected. As soon as you create your `LocalVideoTrack` the capturer is started and will continue capturing until the Track is destroyed (deallocated). Any `TVIVideoRenderer`s which are added to the Track will continue to receive frames. Our QuickStart example projects use this technique of creating a single `LocalVideoTrack` and persisting it for the lifetime of the single view controller application. The thing to keep in mind is that the lifecycle of the Track is independent of the Rooms you are connecting to.

> It seemed that the problem was solved. But now, when i reconnect to the same room i was in before, the TVIVideoRenderer does not get any renderSample calls. I see that the TVIVideoRenderer receives his renderFrame calls, but the TVIAudioSink remains silent.

I'm not sure why this is occurring, but there is an important difference between `TVIAudioSink` and `TVIVideoRenderer` when it comes to dealing with Local Tracks. Unfortunately, due to the way the underlying WebRTC media engine works audio is simply not being captured until you join a Room.

This is explained in the [README](https://github.com/twilio/video-quickstart-swift/tree/2.0.0-preview/AudioSinkExample#known-issues) for our TVIAudioSink example app. To quote myself:

"Local audio samples are not raised until at least one underlying WebRTC PeerConnection is negotiated. In a Peer-to-Peer Room it is not possible to record or recognize audio until at least one other Participant joins. The same limitation does not apply to Group Rooms where there is a persistent PeerConnection with Twilio's media servers."

> If i restart the app and then connect to the same room again, the TVIAudioSink works as intended.
My guess is that there is something wrong with the disconnect, so a new connection after the disconnect might cause some issues.
> Why is TVIAudioSink->renderSample not beeing called the second time i connect?

What type of Room are you using (i.e. Group or Peer-to-Peer)? If you're using a Group Room then you should begin receiving `renderSample` callbacks shortly after joining the Room. If you're in a Peer-to-Peer Room you need at least one other Participant to be present. In both cases you need to include your `TVILocalAudioTrack` in your `TVIConnectOptions` like so:

```.swift
        let connectOptions = TVIConnectOptions.init(token: accessToken) { (builder) in
            if let audioTrack = self.localAudioTrack {
                builder.audioTracks = [audioTrack]
            }
        }
```

As I mentioned earlier you may want to look at our example app for `TVIAudioSink`. Unfortunately it uses our 2.0.0-preview releases but it should give you a sense for the intended usage of the APIs.

https://github.com/twilio/video-quickstart-swift/tree/2.0.0-preview/AudioSinkExample

Let me know if this resolves the issue you're having. If not, I'm happy to provide more assistance.

Best,
Chris Eagleston

**Comment by artemtarassov** [comment]
Hi
@ceaglest ,
thank you for your quick reply.
The room type is Group and i always have 2 participants in the room. `renderSample` is still not beeing called. But the participants Data/Events are beeing shared between all users. So basically everything works but `renderSample`.

Do you have any other idea what the problem might be? I can also try to get `AudioSinkExample` running to reproduce the problem. However, the code is quite simple, i don't see anything wrong in the implementation.

Best,
a

**Comment by artemtarassov** [comment]
Ok it seems that i had an AVPlayer in the background that was causing the problem. Even though it was muted and had no audio, i was able to remove it and get the `renderSample` after.

**Comment by ceaglest** [comment]
That's great to hear @artemtarassov! 

FYI, our latest 2.0.0-preview8 release has an API where you can explicitly enable or disable the audio device used by TwilioVideo to prevent these types of conflicts while you are using AVPlayer. See [TVIDefaultAudioDevice](https://media.twiliocdn.com/sdk/ios/video/releases/2.0.0-preview8/docs/Classes/TVIDefaultAudioDevice.html) for more information.

If you've got things working now, is there anything else I can help with?

Cheers,
Chris Eagleston

**Comment by artemtarassov** [comment]
I've got it working, thanks!

**Comment by ceaglest** [comment]
Great, closing this one out.
