### ISSUE TITLE
Video Quality Recovers Very Slowly

### ISSUE THREAD

**Issue by sdenardi** [twilio/video-quickstart-swift#247]
### Description

Our app is designed for and works well with video rooms having more than 2 participants, while only showing one remote participant's video at a time. After several minutes spent on the video call, one of the participant's video quality will inevitably drop sharply, as a result of a network hiccup I assume. The issue is that the video quality isn't restored back to the original quality as fast as I'd imagine (and what I've come to expect from using other video apps such as FaceTime, Hangouts, Skype, etc.).

It should be noted that audio quality never suffers, nor does temporal resolution.

I've been able to reproduce this issue most often when there are more than 2 participants in the room, but I've experienced it with a 2-person video call a few times. During our testing, the participants have been in environments with strong WiFi and good internet connection. To quickly reproduce the issue, we've had a participant move out of the WiFi's optimal coverage area, see the quality degradation, and have them move back to next to the router. 

Questions:
- Is the media engine's bandwidth estimation affected by the number of participants in a room?
- Is there any way to increase the frequency that the media engine samples the network, in hopes of restoring video quality faster?

### Steps to Reproduce

1. Join room with multiple participants (can be peer-to-peer, have experienced problem with both).
2. Wait a few minutes for one participant's connection to dip, resulting in degraded quality.
3. Watch that participant's video quality very slowly (after several minutes).

#### Code

```swift
// starting local video track
camera = TVICameraCapturer(source: .frontCamera, delegate: self)
    let videoConstraints = TVIVideoConstraints { (constraints) in
        constraints.maxSize = TVIVideoConstraintsSize1280x720
        constraints.minSize = TVIVideoConstraintsSize640x480
        constraints.maxFrameRate = TVIVideoConstraintsFrameRate30
        constraints.minFrameRate = TVIVideoConstraintsFrameRate15
    }
    localVideoTrack = TVILocalVideoTrack(capturer: camera!,
                                         enabled: true,
                                         constraints: videoConstraints,
                                         name: "frontCamera")

// connecting to the room
let connectOptions = TVIConnectOptions(token: token!) { (builder) in
    builder.audioTracks = self.localAudioTrack != nil ? [self.localAudioTrack!] : []
    builder.videoTracks = self.localVideoTrack != nil ? [self.localVideoTrack!] : []
    builder.roomName = self.roomName
    builder.preferredAudioCodecs = [ TVIAudioCodec.opus.rawValue, TVIAudioCodec.ISAC.rawValue ]
    builder.preferredVideoCodecs = [ TVIVideoCodec.H264.rawValue, TVIVideoCodec.VP8.rawValue ]
    builder.encodingParameters = TVIEncodingParameters(audioBitrate: 0, videoBitrate: 20 * 1024 * 1024)
}
room = TwilioVideo.connect(with: connectOptions, delegate: self)
```

#### Expected Behavior

Quality to improve immediately once the network recovers.

#### Actual Behavior

Quality takes several minutes to restore to initial.

#### Reproduces How Often

Always after a few minutes of a room with >2 participants, occasionally with a 2-person room.

#### Video iOS SDK

2.0.0-beta3 (happened on 2.0.0-beta2, as well as 1.x releases)

#### Xcode

9.2 (9C40b)

#### iOS Version

All 11.2.6

#### iOS Devices

iPhone 7, iPhone 8 Plus, & iPhone X

**Comment by ceaglest** [comment]
Hi @sdenardi,

Thank you for the in depth report! I'm going to dig into this further tomorrow, but for now I just wanted to ask a couple of follow up questions.

> Always after a few minutes of a room with >2 participants, occasionally with a 2-person room.

Is it a Peer-to-Peer or Group Room?

Could you share a Room SID where you experienced the issue? This will allow me to grab media quality stats over time and have a closer look at things like which codecs were negotiated.

Regarding bandwidth limits, I would try a significantly smaller value for 720p publishing. You probably don't want to exceed 2-3 megabits per second in a live streaming environment:

```.swift
    builder.encodingParameters = TVIEncodingParameters(audioBitrate: 0, videoBitrate: 2 * 1024 * 1024)
```
> Quality takes several minutes to restore to initial.

Beyond bandwidth concerns, there are some paths in the video pipeline that are not quite optimal when downscaling 720p due to network conditions. I'm worried that the system is getting stuck at a point where it doesn't want to return to the original quality level due to a priority inversion adding some delay.

We've recently landed some threading improvements in [1.3.11](https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-1x#1311-february-26-2018) which will help with H.264 in 2.0.0-beta4. I'll be paying close attention to your use case, to see what other bottlenecks exist in the video pipeline and how we can fix them.

Best,
Chris

**Comment by ceaglest** [comment]
Hi,

I'm sorry that I've been quiet on this issue. It's still top of mind, and I'm returning to it now that we've landed some performance related changes in our internal 2.0 builds.

> I chose 720p because we did notice a marked improvement over the default. Would you recommend lowering the maxSize to 540p?

Yes, I would definitely recommend giving 540p a try, and reducing to ~1.5 - 2.0 Mbps at this resolution. This should put less stress on the system when downscaling does need to occur.

I'll post more on this ticket once I've had a chance to dig in a little deeper.

Best,
Chris

**Comment by sdenardi** [comment]
Thanks Chris. I've definitely noticed better performance setting the max resolution to 540p. While not knowing the internals of the media engine, this makes sense because the ceiling to return quality to is lower.

Look forward to hearing more about what you find. 

- Sanders

**Comment by sdenardi** [comment]
Hi @ceaglest, I just checked out the 2.0.0-beta4 and the video quality has significantly improved from our early testing. Thank you for your help and hard work.

**Comment by ceaglest** [comment]
Hi @sdenardi,

My apologies, I should have pinged you when the release went out. The major change on the client side was adopting a more modern threading model within the WebRTC media engine.

Best,
Chris

**Comment by sdenardi** [comment]
@ceaglest No worries. The Changelog, coupled with your earlier response about the threading of the media engine, gave me a good sense of what to look for.

**Comment by treyrich** [comment]
@ceaglest we just started investigating a similar issue to this, and actually we wanted to go a step further and pause video transmission with a significant enough low-bandwidth situation occurs. This is my first foray into the `getStatsWithBlock` method, but from what I can tell in a DRAMATICLY low bandwidth situation the framerate reported in `getStatsWithBlock` doesn't change at all, despite the video just crawling on the screen. Is there another method that can be used to accurately determine the correct time to pause video transmission?

Also, perhaps more-so on topic for this issue, I have noticed in our testing that the video dimensions actually drastically decrease immediately after the network speed has improved. So if I throttle the iPhone's network using the Network Link Conditioner, then turn off the Network Link Conditioner, the frame rate drops well below the point it was at with the conditioner enabled.

Thanks, please let me know if you'd like me to create a new issue for the first question in this comment.

**Comment by ceaglest** [comment]
Hi @treyrich,

> This is my first foray into the getStatsWithBlock method, but from what I can tell in a DRAMATICLY low bandwidth situation the framerate reported in getStatsWithBlock doesn't change at all, despite the video just crawling on the screen. Is there another method that can be used to accurately determine the correct time to pause video transmission?

There is a configuration internally in WebRTC which might help you out. I will have a look at this.

As for `getStats:` are you looking at [TVILocalVideoTrackStats.frameRate](https://twilio.github.io/twilio-video-ios/docs/latest/Classes/TVILocalVideoTrackStats.html#//api/name/frameRate)? You don't want to use the captured frame rate since its not impacted by the network. Your most reliable indicator is probably doing a delta of [TVILocalTrackStats.bytesSent](https://twilio.github.io/twilio-video-ios/docs/latest_1.x/Classes/TVILocalTrackStats.html#//api/name/bytesSent) and checking for a very low video send bitrate.

> Also, perhaps more-so on topic for this issue, I have noticed in our testing that the video dimensions actually drastically decrease immediately after the network speed has improved. So if I throttle the iPhone's network using the Network Link Conditioner, then turn off the Network Link Conditioner, the frame rate drops well below the point it was at with the conditioner enabled.

I will have to double check this case once I'm back in the office Thursday, but this particular issue might be resolved by upgrading to `2.3.0-preview1`. There have been a lot of changes in bandwidth estimation, encoding, and quality scaling since `2.2.1` which was based upon an older version of WebRTC.

Best,
Chris

**Comment by treyrich** [comment]
Hey @ceaglest, hope you had a good 4th. I was actually checking the `frameRate` and trying to compare it against the `captureFrameRate` of `TVILocalVideoTrackStats`. I was also looking at the `frameRate` of the remove video track stats. I didn't look at taking a delta of the `bytesSent` though, so I'll see if I can test that out today. Please do let me know about said internal configuration.

Thanks!

**Comment by ceaglest** [comment]
Hi everyone,

Lets use this dedicated ticket to discuss pausing video transmission: https://github.com/twilio/video-quickstart-swift/issues/299

As for the original issue of video recovering very slowly, there should be improvements in our [2.3.0](
https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-2x#230-august-7-2018) release, which is based upon WebRTC 67 and has improved bandwidth estimation. If you're experiencing this issue in the field I highly recommend an upgrade.

Best,
Chris

**Comment by ceaglest** [comment]
Closing now that 2.3.0 has been available for some time with improved BWE.

**Comment by ashaykho** [comment]
h

**Comment by ashaykho** [comment]
I'm having issues where the quality is low and the video freezes often. How do I detect a freeze/improve quality?

**Comment by ceaglest** [comment]
Hi @ashaykho,

Can you open a separate issue so that we can investigate your Rooms further?

Thanks,
Chris
