### ISSUE TITLE
Is there any way to get Twilio recording in other formats like mp4. 

### ISSUE THREAD

**Issue by nomimalik1769** [twilio/video-quickstart-swift#300]
I am having issue playing MKV format which I am getting from twilio server. I want to play those but unable to play them on browser they are directly downloading . is there any way so I can get those files in mp4 format.

Any help will be appreciated.

**Comment by piyushtank** [comment]
@nomimalik1769 Yes we support many containers. But mkv just holds the *original* recording without transcoding, what you're asking for is a Transcode to a new format. Have you tried our `video-composer` APIs ? see [[this](https://www.twilio.com/docs/video/api/compositions-resource)] for more information.

Let me know if you have any questions.

**Comment by nomimalik1769** [comment]
Our App backend is developed in C# .net. I have searched all over that link you provided I can't seem to find any reference or code for C#.net. Can you please help me regarding this.

**Comment by nomimalik1769** [comment]
@piyushtank ???

**Comment by ceaglest** [comment]
Hey @nomimalik1769,

We do offer a C# helper library, but it appears that the code snippets for the composition APIs do not include C#. I've asked our video recordings team to take a pass and update the docs, because these particular examples require some manual intervention.

Until then you can find the C# helper library [here](https://www.twilio.com/docs/libraries/csharp-dotnet).

Sorry for the confusion,
Chris
