### ISSUE TITLE
Signaling Error

### ISSUE THREAD

**Issue by sara-shokry** [twilio/video-quickstart-swift#35]
Hi,
I have this error in logs 
ERROR:TwilioConversations:[Signaling]:RESIP::TRANSPORT: Got TLS read ret=0 error=6 error:00000006:invalid library (0):OPENSSL_internal:public key routines
but i could make call normally but don't know what's this error relate or affect

**Comment by ptankTwilio** [comment]
Hi Sara,

Thanks for reaching out to us. Video SDK log this error when the signaling connection gets dropped with the server. But, it is hard to say the reason why the connection got dropped without looking into the logs. In order to debug this further, can you please provide following -

1. Which Video SDK version are you using ?
2. Can you enable Debug Logs on module Core and send it to us?

Regards,
Piyush Tank

**Comment by sara-shokry** [comment]
1. SDK version:   0.25.0
2. logs in Debug Logs on module Core 

> `INFO:TwilioConversations:[Core]:Adding X-Twilio-AccessToken ...
> ERROR:TwilioConversations:[Signaling]:RESIP::TRANSPORT: Got TLS read ret=0 error=6 error:00000006:invalid library (0):OPENSSL_internal:public key routines
> WARN:TwilioConversations:[Core]:Connection terminated: ConnectionTerminated [ V4 54.172.60.92:5061 TLS target domain=54.172.60.92 mFlowKey=55 ]
> `

and more quetion  please , should i use VOIP to receive video calls in background?
Thanks for quick replay.

**Comment by idelgado** [comment]
@sara-shokry This error message is benign. It should have been an info message instead. This happens during registrations in some cases when our backend redirects the connection to another server.

As for your question on receiving video calls in the background, I would recommend you check out our new Video SDK. You can see the latest version in the master branch of this repository. Last month we released the first version of the Video SDK which only requires that you share a room name with participants to connect to a Room, rather than rely on invites which require a long-live connection and not allowed in newer versions of iOS. You can share the room name using whatever mechanism you like, APNS, Firebase, or any existing push implementation you may already be using in your app.
