### ISSUE TITLE
Audio does not work in iOS 12 

### ISSUE THREAD

**Issue by vkey** [twilio/video-quickstart-swift#363]
Hi guys! We use your SDK for video chat and faced with the problem that is described below.

### Description
By event from android device server creating room for two devices (android and iOS). The server creates a room for video call and sends room id to mobile clients. Mobile clients after receiving the room are connected to it. But when we use device with iOS 12 there no audio in video call. At same time in iOS 11 with same code we don't have such problem.

### Steps to Reproduce
1. Android device initiates video call
2. The server creates the room and send it to the mobile clients
3. iOS device gets push notification with room id and shows a call with CallKit. After the user takes the call we join to the room
4. Video Call is established but participants do not hear each other

#### Code
Just using the quickstart code. If you need some code example we are ready to provide them.

#### Expected Behavior
The Video Call is established and participants hear each other.

#### Actual Behavior
The Video Call is established and participants see but do not hear each other in iOS 12.

#### Reproduces How Often
100%

#### Logs
If logs are needed what level and at what point are logs needed?

### Versions
Devices:
iPhone X running 12.0.1
android version 4.4.2

SDKs:
iOS SDK Version 2.7.0
android SDK (Version 2.0.2)
server php SDK (Version 5.21.0)

**Comment by polurezov8** [comment]
Hi Twilio Team! Faced with the same problem, this is the only thing that stops our team from release. We hope for your efficiency and help in the decision.

**Comment by ceaglest** [comment]
Hi @vkey,

It looks like you closed the issue, were you able to figure out why the iOS device was not producing audio?

> If logs are needed what level and at what point are logs needed?

Usually debug level logs from before you connect, to after the problem occurred would be good.

Hi @polurezov8,

> Faced with the same problem, this is the only thing that stops our team from release.

We aren't aware of any blanket issues where audio simply doesn't work on iOS 12. Can you please be more specific about what you are trying, with what hardware, version of our SDK, and what code (is it also 2.7.0)? If the issue is reproducible on our QuickStart, what steps should I take?

Best,
Chris
