### ISSUE TITLE
[Feature Request] Ability to get real time quality statistics

### ISSUE THREAD

**Issue by andschdk** [twilio/video-quickstart-swift#366]
Hi,
I imagine this being a feature request.

Imagine one wanting to react to changes in video or audio quality, e.g. show a message/icon or stop the video track if audio quality drops...
Currently I do not see an easy way for doing so.

In a similar product (OpenTok) I found something that enables this. It is still in beta, but maybe you would find it inspiring. https://tokbox.com/developer/sdks/ios/reference/Classes/OTPublisherKit.html#//api/name/networkStatsDelegate

Stats could include:
- Total audio and video packets lost
- Total audio and video packets received
- Total audio and video bytes received

Related issues:
#137 
#299 

Do you know if such feature is on the roadmap or if there's any easy workarounds to achieve this?

Thanks.

**Comment by ceaglest** [comment]
Hi @andschdk,

> Imagine one wanting to react to changes in video or audio quality, e.g. show a message/icon or stop the video track if audio quality drops...
Currently I do not see an easy way for doing so.

Ever since our 1.0 releases we have allowed you to get media statistics for all of the Tracks that you are publishing / subscribing in a Room. Take a look at [-[Room getStatsWithBlock:]](https://twilio.github.io/twilio-video-ios/docs/latest/Classes/TVIRoom.html#//api/name/getStatsWithBlock:) to get started (there isn't public sample code at the moment).

However, we are also working on [Network Quality APIs](https://www.twilio.com/docs/video/using-network-quality-api) that might solve this problem more easily for you. They APIs assign Participants a quality score from 1-5 based upon their network conditions. Network Quality is available for JavaScript today, and this is the next feature that we are working on for iOS.

Best,
Chris

**Comment by andschdk** [comment]
Hi @ceaglest,
I guess I have to open my eyes. Sorry for that.

Looking forward for the NQA APIs 👏 . Thanks.

**Comment by ceaglest** [comment]
Its easy to miss features with no sample code, we will work on that. Have a good one!

Chris

**Comment by spacedema** [comment]
Hi, Chris!

Is there an info about NQA APIs release dates?

Regards,
Sergey
