### ISSUE TITLE
Replay Kit Conference not working

### ISSUE THREAD

**Issue by rashidabbas** [twilio/video-quickstart-swift#383]
Hi I am using replay kit example provided by you and I am facing issue during start conference when I hit start conference button I show an error like. "Recording interrupted by multitasking and content resizing".

please help thanks.

**Comment by ceaglest** [comment]
Hi @rashidabbas,

Since there is an existing issue, would you mind if we continued the discussion there?

https://github.com/twilio/video-quickstart-swift/issues/322

If you could let us know more information, like what device, and OS version you are testing on that would be helpful in diagnosing the problem.

Thanks,
Chris
