### ISSUE TITLE
room connection failed.

### ISSUE THREAD

**Issue by alldev0825** [twilio/video-quickstart-swift#44]
When I enter room text and click connection button, after some minutes always I failed to connect that room receiving message "Failed to connect to room with error".
I tried to know why it is happened as following:

```
func room(_ room: TVIRoom, didFailToConnectWithError error: Error) {
        logMessage(messageText: "Failed to connect to room with error")
        print("error=\(error)")        
        self.room = nil
        self.showRoomUI(inRoom: false)
    }
```

But the program is crashed in print sentence.
I received the token and am successful in showing camera preview.

**Comment by paynerc** [comment]
Hey @alldev0825,

I'm sorry to hear that you are experiencing this crash. My assumption is that you are using the first beta. We had a known issue where, even though the API contract stated otherwise, the `error` object being provided was sometimes `nil`. We have fixed that with Beta 2 that was released last week.

So that should solve the issue with the crash. The next question is why you are failing to connect to the room? I'm concerned that the token you are generating is invalid, which is why the room is failing to connect. Would you be able to turn on `verbose` logging and provide so we can figure out what is going on?

To turn on verbose logging you would just need to add a call to `TVIVideoClient.setLogLevel(.all)`. I usually do this in `func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool`

**Comment by Artheyn** [comment]
Hey @paynerc,

I was facing the same issue and thanks to your message I've fixed it by upgrading the library from Beta 1 to the latest Beta (Beta 3). I think you can close this issue.

Thanks for your help and congrats for this "delightful to implement" SDK.

Keep up the good work :)
Cheers,

**Comment by paynerc** [comment]
@Artheyn Awesome to hear that that helped you. And thanks for the kind words. We are striving to make this super easy to use while still super powerful.

Thanks again!

**Comment by ceaglest** [comment]
Closing this issue, since it has been reported as resolved in beta3.

**Comment by XiaoGuiDeveloper** [comment]
I am facing this issue

**Comment by JiyarMahmod** [comment]
iam facing the same issue...

**Comment by ceaglest** [comment]
Hi @JiyarMahmod, @XiaoGuiDeveloper,

This is a very old issue and since our 1.0 betas we've changed to signaling over TLS/443. If you're still having problems with a newer version of the SDK, would you mind opening another issue and letting us know what devices/sdk version/region you are in?

Best,
Chris

**Comment by ceaglest** [comment]
Okay @JiyarMahmod lets discuss this further. Can you please create a new issue?

https://github.com/twilio/video-quickstart-swift/issues/new

**Comment by JiyarMahmod** [comment]
I Will create this New issue as soon as i get of work so in 1h or so thank You for trying to help i Will let You know when i have create this New issue thanks @ceaglest

**Comment by JiyarMahmod** [comment]
@ceaglest hi there i hope this is enough information but here is the thread https://github.com/twilio/video-quickstart-swift/issues/304 just comment if you need some more information or if you have the solution. Thanks!
