### ISSUE TITLE
Switch default audio out to iPhone speaker instead of earpiece

### ISSUE THREAD

**Issue by nah2015** [twilio/video-quickstart-swift#55]
Hello, I have everything set up and running as I'd like it to other than the audio output.  With video chat, it seems it would be better to have the audio default to speaker output doesn't it?  Currently mine defaults to the earpiece.

Any insight would be appreciated.  I've seen some references to the following

`AVAudioSessionPortOverride.Speaker`

**Comment by nah2015** [comment]
I'm guessing I have to edit TVIAudioController.h ??

**Comment by ptankTwilio** [comment]
Hi @nah2015 

Thanks for reaching out to us.

Video SDK sets `AVAudioSessionModeVideoChat` as the default audio session mode.  By default, for  AVAudioSessionModeVideoChat, iOS routes audio to speaker if an earpiece is not attached, otherwise the audio gets routed to the earpiece.  However, you can override this behavior and route audio to speaker using Video SDK APIs in following way -

let localMedia = TVILocalMedia()
let audioController = localMedia.audioController
audioController.audioOutput = .videoChatSpeaker

Let me know if you have any questions.

Regards,
Piyush

**Comment by nah2015** [comment]
Got it!  Thank you very much and happy holidays!
